Feature/new design request strains
AndersenLab/CAENDR pull request #189
Opened 2023-04-25 22:07 UTC by orzut

Please test a cart for all the following user stories (and for any edge cases you come up with):
As a [ ROLE ] I want to do [ACTION]. 
- As a non-logged user, I want to initiate a cart and be able to add/remove stuff to it.
[PROMOTION] of a cart to be assigned to a user. 
- As a non-logged user, I want to initiate a cart and be able to add/remove stuff to it, and to login to the site and have the cart be updated with my user id/email. This way the cart knows it belongs to me. 
- As a logged-in user, when i navigate to the order page, I want my existing cart to show up (if it exists). 
- If a user logs in on a second device, I want my existing cart to show up. 
- As a non-logged-in user in a second device, [@vince] 
- As a non-logged-in, I want to navigate to the order page. A new cart is created and it is empty. I then login, the cookie will map to an empty cart (unassigned to a user), and my previously stored cart is now populated. [edge case].

2023-04-26 16:39 UTC, r-vieira approved these changes
looks good!

2023-05-02 23:47 UTC, natalieroman requested changes
Hi Orzu, this looks great! 

Sorry for leaving so many comments. I realized when I was reviewing this that when I handed off the designs to you, I didn't do a great job of including all the Bootstrap info you'd need to do this without custom CSS. And I maybe didn't do a great job of explaining how to use the Bootstrap grid for responsive layouts. So apologies for that-- I'm still learning a lot here. 🙂

I suggested in a comment that we discuss the Strain Catalog page face-to-face to go over some tips for responsive design, so maybe we can chat in-person on Wednesday. As always, please let me know if any of my comments are confusing or unclear!

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/_includes/footer.html
> +        <a href="/"><img src="/static/img/caeNDRLogo.png" class="d-block img-fluid mx-auto footerImage" alt="Caendr Logo"></a>
Thanks for adding the alt text here! I think that "Home" would make more sense here, because the logo allows the user to go back to the homepage, so we'd want a way to communicate that to users of screen readers. Otherwise, the logo doesn't communicate any information to a screen-reader user ([more info](https://www.smashingmagazine.com/2021/06/img-alt-attribute-alternate-description-decorative/#supplemental-icons/))

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/_includes/navbar.html
> +        <a href="/"><img src="/static/img/caeNDRLogo.png" class="img-fluid" alt="Caendr Logo"></a>
Same comment here -- I think it makes more sense to use "Home" as the alt text.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +    <div id="tableContainer">
In general, it's best practice to use Bootstrap for layouts and styling and to avoid creating custom CSS if you don't have to. It can be really helpful to refer to the design system to see how similar styles were achieved there. For this section, I'd recommend taking a look at the [Request Strains pattern](https://github.com/northwestern-mti/caendrbootstrap/blob/main/src/requestStrains.html) to see how the grey background boxes were achieved. 

So here, instead of using the `tableContainer` custom CSS, I'd recommend using the following: 

```
<div class="col-12 col-md-9 p-5 mb-5 mx-auto  rounded shadow-sm text-bg-light">
...
</div>
```

- `col-12` and `col-md-9` use the [Bootstrap grid system](https://getbootstrap.com/docs/5.2/layout/grid/#grid-options) to control the width of the container. `col-12` tells the container to take up the full width of the grid (12 columns) on extra small devices (mobile). `col-md-9` tells the container to take up 9 columns of width on medium and larger devices (desktop).
- `p-5` sets the padding at the highest level (1 is lowest, 5 is highest) on all sides of the container. 
- `mb-5` sets margin-bottom on the container
- `mx-auto` will automatically horizontally center the container
- `rounded` creates the slightly rounded corners
- `shadow-sm` adds a small amount of drop shadow
- `text-bg-light` sets the background color

Using these classes will make it easier to change things on a global level if we need to at a later date. For example, if we decide to change the color of `text-bg-light` in a future redesign, we can do that by simply editing the Bootstrap CSS files, instead of having to change hex values on several different pages.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +        <table class="table table-striped m-4" id="orderTable">
Please be sure to wrap all tables in a `table-responsive` div to ensure tables adjust appropriately across different screen sizes. Plus, you then won't need to set the max-width with custom CSS. 

We should also include a caption for accessibility, to describe the purpose of the table for users of screen readers.

```
<div class="table-responsive">
    <caption class="visually-hidden">A list of items included in your shopping cart.</caption>
    <table> ... </table>
</div>
```
Might also be good to remove `m-4`, as I noticed it causes the table to "wiggle" once you make the table responsive.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +        background-color: #d9dbf8;
You can use Bootstrap variables to ensure that colors remain consistent when there's not an easy Bootstrap class available (I know there isn't for this color). This is the same color as the footer, so you could use `background-color:var(--bs-footerBg)`.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +    h3 {
I don't think you need this, because I don't see any `<h3>`s on the page. Plus, it's conflicting with the text in the footer, causing the `<h3>`s there (tools, data, about us, cite CaeNDR) to be oddly centered.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +        <div class="col">
Again, I'd use Bootstrap on this div to add the styling, instead of using custom css on the `shippingInfo` div below. 

This should also mean you won't need to use the custom CSS with `form-submit` to set the margin.

```
 <div class="col text-bg-light shadow-sm rounded p-5 m-3">
...
</div>
```

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +        <div class="col">
Same comment here as the "Shipping Info" div. I'd recommend the below instead of custom CSS: 

```
 <div class="col text-bg-light shadow-sm rounded p-5 m-3">
...
</div>
```

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +                        <button type="button" class="icon-btn" data-toggle="modal" data-target="#paymentInfoModal" aria-label="Payment information"><i class="bi bi-info-circle-fill" id="payment-info-
You don't need custom CSS to set the color of the icon. Remember that an icon here is just text, so you can use all the usual Bootstrap classes to set text color. This will help ensure the colors used are consistent across the site.

`<i class="bi bi-info-circle-fill text-secondary" aria-hidden="true"></i>`

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +                    <td class="delete">
I don't think you need custom css here. All buttons should use the `btn` class for Bootstrap, which will remove the weird grey box. And then you can use `text-danger` to set the icon color. 

```
<button type="button" class="btn" info={{ item.name }}>
   <i class="bi bi-trash-fill text-danger" class="delete-icon" aria-hidden="true"></I>Delete
</button>
```

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
Please be sure to use the `btn-close` class to ensure this is styled consistently with other modals used on other pages.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
Please be sure to use the `btn-close` class to ensure this is styled consistently with other modals used on other pages.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order.html
> +                    <button type="button" class="btn btn-info" id="goBack">
I'd recommend not using custom CSS for the text color here. Usually, if you want to set the text color on a button, I'd recommend doing the following: 

```
<button type="button" class="btn btn-info text-light" id="goBack">
     <i class="bi bi-slash-circle-fill"></I> No, go back.
</button>
```

But looking at this now, I think it's best to leave the text black (what happens when you remove the custom CSS) for accessibility purposes.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
>  <div class='col lg-9 col-md-9 col-sm-9 col-xs-9'>
I think there's too many responsive column sizes declared here that aren't needed. All that should be needed is: 

```
<div class="col col-md-9 mx-auto">
...
</div>
```
The `mx-auto` will also make sure that this is centered correctly on the page.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
>    <div class="panel panel-default">
`panel` isn't supported in Bootstrap 5 anymore, so I don't think this is adding anything stylistically, so this `div` can be removed.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +        <h2 class="panel-title">{{ invoice }}</h2>
You can remove `panel-title`.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +      <div class="d-flex justify-content-between mb-4 panel-heading">
You can remove `panel-heading`

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +          <button type="button" class='btn btn-primary btn-block hidden-print' onClick="window.print()">
Looks like `hidden-print` is no longer supported in Bootstrap 5. Should use `d-print-none` instead ([more info](https://getbootstrap.com/docs/5.2/utilities/display/#display-in-print).)

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +      <div id="container">
Same as similar comments made elsewhere, I'd avoid using custom CSS if possible. Should use the Bootstrap classes listed below instead: 

```
<div class="text-bg-light rounded shadow-sm p-5 mb-5">
     ...
</div>
```

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +          <table class="table table-hover table-striped" style="table-layout: fixed">
Please be sure to wrap all tables in a responsive div and include a caption for accessibility.

In addition, if you make the table responsive and just add some Bootstrap padding, you won't need the custom CSS to control the width and margin for the table.

```
<div class="table-responsive px-5">
          <table class="table table-hover table-striped">
             <caption class="visually-hidden">A list of items ordered</caption>
              ...
          </table>
</div>
```

- `px-5` allows you to set the padding on only the left (start) and right (end) of the container.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +      <h4>To complete your order</h4>
This should be an `<h2>` for accessibility.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +      <div id="mailInfo">
Similar to other comments, you can use the following Bootstrap to style everything here (except for the background color - will comment on that above shortly). 

```
<div class="ps-5">
      <div class="border-start border-primary border-2 p-3">
           ...
      </div>
</div>
```

- I added the outer `div` with the class of `ps-5` to achieve the indent effect. This sets the padding for the left (start) side of the container
- `border-start` adds border only on the left (start) side of the container
- `border-primary` sets the color
- `border-2` controls the border width

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +      background-color: #d9dbf8;
I'd use the Bootstrap variable to ensure that the color is consistent across the site. 

`background-color: var(--bs-footerBg);`

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +        <p class='hidden-print'>Please contact us if you have any questions (<a href='mailto:cendr@northwestern.edu'>cendr@northwestern.edu</a>; 847-467-4382).</p>
Similar to other comments, need to use `d-print-none` now.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/order/order_confirm.html
> +          <li>Make a check payable to Northwestern University and write 'CeNDR' and your invoice number in the memo field.</li>
Should be "CaeNDR"

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/strain/landing_page.html
> +    <h1>Request Strains</h1>
It's probably best to set the title of the page programmatically in strains.py to be consistent with the rest of the site and to make proper use of the default.html layout rather than declaring it explicitly here.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/strain/landing_page.html
> +    h2, h3 {
This custom CSS is creating some conflicts with the footer text so should be removed. I'll add some comments below on how to achieve the same effects using Bootstrap classes.

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/strain/landing_page.html
> +    <h2>Please choose your affiliation:</h2>
Should use the following instead of custom CSS: 

`<h2 class="text-dark text-center"> ... </h2>`

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/strain/landing_page.html
> +        <div class="card shadow cardBorderBottom">
Would recommend adding some padding to make these cards look a little bit more consistent with cards used elsewhere on the site. 

```
<div class="card py-5 shadow cardBorderBottom">
     ...
</div>
```
- `py-5` sets padding only on the top and bottom of the container

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/strain/landing_page.html
> +                    <h3 class="card-title">Academia</h3>
Would recommend using the below instead of custom CSS: 

`<h3 class="card-title text-dark"> ... </h3>`

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/strain/landing_page.html
> +                    <h3 class="card-title">Industry</h3>
Would recommend using the below instead of custom CSS: 

`<h3 class="card-title text-dark"> ... </h3>`

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/strain/landing_page.html
> +        <div class="card shadow cardBorderBottom">
Would recommend adding some padding to make these cards look a little bit more consistent with cards used elsewhere on the site. 

```
<div class="card py-5 shadow cardBorderBottom">
     ...
</div>
```
- `py-5` sets padding only on the top and bottom of the container

2023-05-02 23:47 UTC, natalieroman commented on src/modules/site-v2/templates/strain/catalog.html
This looks great! However I noticed that there are some responsive layout issues, especially on the "Individual Strains" tab (see screenshot below). 

I addressed these issues in the ["Request Strains" page pattern](https://github.com/northwestern-mti/caendrbootstrap/blob/main/src/requestStrains.html) in the design system. That page pattern also reduces the need for writing custom CSS. 

Rather than trying to address things on a line-by-line basis, let's review the design system for this page together so I can give some responsive layout tips that'll be easier for me to explain face-to-face (and possibly with the aid of a whiteboard because I like visuals). 🙂

<img width="709" alt="image" src="https://user-images.githubusercontent.com/95776786/235807428-24386b35-327e-46d3-8fd1-27056f7063ee.png">

2023-05-08 16:47 UTC, vlagrassa approved these changes
Looks good to me!

2023-05-08 18:06 UTC, natalieroman approved these changes
Looks great! Thanks for making all the markup/styling changes.

2023-05-08 19:35 UTC, r-vieira approved these changes
Looks good!

2023-05-08 20:21 UTC, closed without merging