Small Gene Search Fixes
AndersenLab/CAENDR pull request #372
Opened 2023-07-13 18:41 UTC by vlagrassa

- Fix back-end sorting of results:
  - Use a more natural sorting algorithm (e.g. `lin-2` before `lin-10`)
  - Sort before truncating (taking top 10), so most relevant results actually appear
- If query is just species-specific gene prefix, search for it directly instead of removing it -- otherwise query would match all genes (equivalent to searching for `""`).  Otherwise, the prefix is removed from the search.
- Display error message in dropdown if query fails (distinct from empty results)
- Add small margins around dropdown messages, so they look less awkward

2023-07-17 16:01 UTC, r-vieira requested changes
see inline comments (main one is about exposing the error to the end-user)

2023-07-17 16:01 UTC, r-vieira commented on src/modules/site-v2/templates/_scripts/igv-browser.js
> +      console.log('Error loading track ' + track_name + ': ', error)
should this error be exposed to the end-user?

2023-07-17 16:01 UTC, r-vieira commented on src/modules/site-v2/templates/tools/genome_browser/gbrowser.html
> +const gene_search_div_ids = {
minor semantic/naming detail -- consider using `..._element_...` instead of `..._div_...`. E.g. `gene_search_element_ids = `

2023-07-17 16:01 UTC, r-vieira commented on src/modules/site-v2/templates/tools/genome_browser/gbrowser.html
> +  "table":   "#g-search-table",
semantic detail -- if these are `ids`, then they shouldn't include the `#` in the values. On the other hand, if these are `selectors`, then the `#` should be included.

2023-07-18 19:36 UTC, vlagrassa commented on src/modules/site-v2/templates/tools/genome_browser/gbrowser.html
> +  "table":   "#g-search-table",
Fixed in https://github.com/AndersenLab/CAENDR/pull/372/commits/7031c98c648bc623a016dd431881c4189573db16

2023-07-18 19:37 UTC, vlagrassa commented on src/modules/site-v2/templates/tools/genome_browser/gbrowser.html
> +const gene_search_div_ids = {
Fixed in https://github.com/AndersenLab/CAENDR/pull/372/commits/7031c98c648bc623a016dd431881c4189573db16

2023-07-18 22:05 UTC, vlagrassa commented on src/modules/site-v2/templates/_scripts/igv-browser.js
> +      console.log('Error loading track ' + track_name + ': ', error)
Good question... if there's an error getting the track, the IGV Browser will show a pop-up with the full URL.

Might be helpful for us to log somewhere if there's an error?  Or just ignore it?

2023-07-20 21:27 UTC, r-vieira commented on src/modules/site-v2/templates/_scripts/igv-browser.js
> +      console.log('Error loading track ' + track_name + ': ', error)
Got it. In this case, we want to capture it in Sentry.IO. (By default SentryIO will track JS exceptions at the top level. SentryIO might also have helper functions that let you track a single event, if that helps). In short, we should be able to find this error in SentryIO and use automated notifications so we are aware of it.

2023-07-20 21:27 UTC, merged

2023-07-20 21:27 UTC, r-vieira commented
See note about having SentryIO capture the error (missing IGV track) so we can automate handling on our side.